config/routes.rb
Rails.application.routes.draw do

  resources :favorites
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :posts
  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord

  validates_presence_of :make, :model, :year, :trim

  def self.search(search)
    where("Car search", "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates_presence_of :name
    has_many :favorites 
    
  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DeviseWhitelist

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?    
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    
  end

  def show

  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  access all: [:show, :index], user: {except: [:new, :create, :update, :edit, :destroy]}, admin: :all
  
  def index
    @posts = Post.all
    if params[:search]
      @search = Post.search(params[:search]).order("created_at DESC")
    else 
      @search = Post.all.order("created_at DESC")
    end
  end

  def new
    @post = Post.new
  end

  def edit

  end

  def show

  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
    if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
    else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully created.'} 
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.permit(:post, :title, :search, :body, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def copyright_generator
    AlonsoViewTool::Renderer.copyright 'Carfo', 'All rights reserved'
  end

  def self.alert
    alert = (flash[:alert] || flash[:error] || flash[:notice])

    if alert
      alert_generator alert
    end
  end

  def self.alert_generator msg
    js add_gritter(msg, title: "Alonso Hernandez Portfolio", sticky: false)
  end
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/favorites/index.html.erb
<%= link_to 'Back to homepage', posts_path %>

app/views/favorites/show.html.erb
<%= link_to 'Back to homepage', posts_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
            <%= video_tag(
                "cars.mp4",
                id: "background",
                autoplay: true,
                loop: true,
                muted: true,
                poster: ""
            )
            %>

            <%= render 'posts/sign_in' %>

            <%= yield %>
            
            <%= render 'shared/footer' %>
            
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
      </div>
  </body>
</html>

app/views/posts/_car.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :make %>
    <%= form.text_field :make, autofocus: true %>
  </div>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :trim %>
    <%= form.text_field :trim %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/_maybe.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :make %>
    <%= form.text_field :make, autofocus: true %>
  </div>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="h4 mb-3 font-weight-normal">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
  <%= post.make %>
  <%= post.model %>
  <%= post.year %>
  <%= post.trim %>
  <%= link_to 'Show', post %>
  <%= link_to 'Edit', edit_post_path(post) %>
  <%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?' } %>
    </div>
  </div>  
</div>

app/views/posts/_search.html.erb
<%= form_tag(posts_path method: :get) do %>
    Car model<%= text_field_tag :search, params[:search], placeholder: "search here" %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<% if @search.blank? %>
  <h4>There are no cars matching your request<%= params[:search] %>.</h4>
<% end %>
    

app/views/posts/_sign_in.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
<% if user_signed_in? %>                  
<h1><%= "Welcome back " %><%= current_user.first_name %></h1>
<% else %>
<h1><%= "Welcome Guest"%></h1>
<% end %>
<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up for a new CarFo account ", new_user_registration_path %>
  <%= link_to "CarFo login", new_user_session_path %>
<% end %>
<% if current_user %>
  <%= link_to "Edit CarFo account profile", edit_user_registration_path %>
<% end %>
<% if current_user %>
  <%= link_to 'View your favorites', favorites_path %>
  <% else %>
  <% false %>
<% end %>
    </div>
</nav>

app/views/posts/edit.html.erb
<h1>Edit Car entry</h1>

<%= render 'car' %>

<%= link_to 'Show', @post %>
<%= link_to 'Back to Homepage', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-4">
      
      <%= render 'search' %>
      <p><%= render @posts %></p>

      <hr>

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Insert new car data</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"></p>

<p>
  <strong>Make:</strong>
  <%= @post.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @post.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @post.year %>
</p>

<p>
  <strong>Trim:</strong>
  <%= @post.trim %>
<p class="btn btn-primary"><%= link_to "<button type='button'>Favorite this car?</button>".html_safe, post_path %></p>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Back', posts_path %>

app/views/shared/_footer.html.erb
<footer class="container">
      <p><%= copyright_generator %></p>
</footer>